### ISSUE TITLE
Update issue/PR with proposal status information

### ISSUE THREAD

**Issue by bumi** [67P/hubot-kredits#11]
To make proposals and the issued Kredits visible from the github issue/pr site hubot could post a comment with the link to the proposal once created or maybe only once accepted.

**Comment by raucao** [comment]
I'm not sure if that's not too noisy in the long run. I think the normal workflow for most people will be to vote on a bunch of proposals every now and then, checking out progress of the project every few days or once per week.

Also, any additional comments would create GitHub notifications for those issues/PRs, with no way to know if there's an actual new comment in there, or just another kredits notification, when looking at one's GitHub notifications.

**Comment by raucao** [comment]
Closing, similar to #10.
