### ISSUE TITLE
Use web3 IPCProvider instead of HTTP Provider

### ISSUE THREAD

**Issue by bumi** [67P/hubot-kredits#13]
As our hubot runs on the same machine as the parity node we could directly connect to parity using the IPC provider - instead of through HTTP. 
I assume this might be a bit more performant and reliable? causing less http requests? 

https://github.com/ethereum/web3.js/blob/master/lib/web3/ipcprovider.js

**Comment by raucao** [comment]
It would probably also enable synchronous method calls, which is a bit of a PITA when it's missing.

**Comment by raucao** [comment]
Not running Parity anymore.
