### ISSUE TITLE
Fix creating proposals from IRC

### ISSUE THREAD

**Issue by bumi** [67P/hubot-kredits#21]
Creating proposals from IRC is currently borken as it used a `createProposal` method that is now in the github integration script: https://github.com/67P/hubot-kredits/blob/master/index.js#L84

maybe we can even remove that feature right now (even though I think I like it) and plan a better one. The main issue right now is that the github username has to be used in the chat message and not the IRC username. 

What do you think?

**Comment by raucao** [comment]
I think it would be easy to add the IRC nicks to the accounts array in the IPFS profile, but it would probably be a bit clunky to use anyway, because you have to cram so much info in one line of chat, with the only one and true sort order and punctuation.

**Comment by bumi** [comment]
it's not to bad imo: `send 1000 Kredits to raucau for hacking hubot`

**Comment by raucao** [comment]
That's a mighty short description and not very useful for presenting it to everybody in the project in the frontend. Also, it encourages bad form like all-lowercase letters, no category, etc., as proven by your example. :)

We'd actually have to validate the contribution against the schema, add error messages for categories, etc.

**Comment by bumi** [comment]
the description could be as long as one wants, though you're right chat messages tend to be short. 
I like the ease of creating a proposal like this. 
Could imagine a category "misc" for such smaller proposals.

**Comment by bumi** [comment]
do we still want this?

**Comment by raucao** [comment]
I think not. Re-open if you disagree. :)
