### ISSUE TITLE
Add support for Gitea org hooks

### ISSUE THREAD

**Issue by raucao** [67P/hubot-kredits#24]
Turns out Gitea is not just pretty great overall, but also perfect for this use case. It supports both organization-wide webhooks, as well as custom label sets that one can select when creating a new repo. So we created a Kosmos label set, with both our preferred normal labels, as well as the kredits labels. See https://gitea.kosmos.org/kosmos/gitea.kosmos.org/labels for example.

The org hook for Kosmos can be created here: https://gitea.kosmos.org/org/kosmos/settings/hooks

**Comment by raucao** [comment]
Actually, the headers in [the webhook doc](https://docs.gitea.io/en-us/webhooks/) suggest that the hooks might be the exact same format as GitHub's hooks. So this might be even easier than I thought.

**Comment by bumi** [comment]
:+1: would be nice to add this soon as the plan was to use more gitea

**Comment by raucao** [comment]
Yes! Also, because we already have some things there, like the Kosmos Chef repo. Should be easy enough. Will give it a shot soon.
