### ISSUE TITLE
Propose Kredits for code reviews

### ISSUE THREAD

**Issue by raucao** [67P/hubot-kredits#49]
On GitHub and Gitea, the reviewers should also get kredits (at least for medium/large contributions).

**Comment by raucao** [comment]
Documenting ideas we discussed so far:

* Collect reviews over a period of time, e.g. one week, then create a single contribution for all reviews on merged PRs from that period
* When one of the reviewers is also assigned to the PR, it means they have done more work on it over time, so they should earn either the full amount, or something between full and review amount.

**Comment by raucao** [comment]
@67P/core @67P/collaborators What do you think would be a good default kredits amount as percentage of the overall amount? (Keep in mind that one should be able to switch from giving review kredits to assigning a co-author.)

**Comment by galfert** [comment]
I think something like 20% might be a good number to start with.

**Comment by raucao** [comment]
Note from weekly call: @bumi, @gregkare, @skddc agree that it's a good number to start with.

**Comment by galfert** [comment]
So far I'm able to accumulate all reviews and the corresponding kredits for a given timeframe.

What should we put in the details of the contribution entry? Just the list of the pull request URLs or all of the payload data for every review?

**Comment by raucao** [comment]
List of URLs seems enough to me. Ideally we can turn it into separate contribution objects in IPFS later, once the kredits API wrapper supports that.
