### ISSUE TITLE
Failing to add contribution (false negative alert)

### ISSUE THREAD

**Issue by raucao** [67P/hubot-kredits#50]
Just happened with one from Gitea (see `kredits@kosmos.chat`):

> I tried to add a contribution for raucao for https://gitea.kosmos.org/kosmos/gitea.kosmos.org/pulls/45, but I encountered an error when submitting the tx:
> 
> replacement fee too low (version=4.0.36)

Quickly checked HAL's wallet, and it contains enough ETH for any amount of fees.

**Comment by bumi** [comment]
"replacement fee too low" is typically when the same transaction is published twice - or a transaction with the same nonce that is.

**Comment by raucao** [comment]
There was no other tx being published close to the same time (or even this entire day). So it must be a problem with nonce management (#28) in general?
