### ISSUE TITLE
[zoom] Configure meeting ID(s) to count

### ISSUE THREAD

**Issue by raucao** [67P/hubot-kredits#55]
Currently, it creates contributions for *any* meetings in the entire Zoom account that the JWT app is registered for, resulting in e.g. 5apps meetings being counted as Kosmos ones.

**Comment by bumi** [comment]
hmm.... does it have a fixed ID? if so it should be easy.

**Comment by raucao** [comment]
Yup: https://wiki.kosmos.org/Main_Page#Weekly_conference_calls

But the implementation should probably be an array/list, so that we can have more than one room. Not very important compared to counting wrong ones though.
